export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST '
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS '
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL '

export const GET_PRODUCT_DETAILS_REQUEST='GET_PRODUCT_DETAILS_REQUEST'
export const GET_PRODUCT_DETAILS_SUCCESS='GET_PRODUCT_DETAILS_SUCCESS'
export const GET_PRODUCT_DETAILS_FAIL='GET_PRODUCT_DETAILS_FAIL'

export const GET_PRODUCTS_BY_CATEGORY_NAME_SUCCESS='GET_PRODUCTS_BY_CATEGORY_NAME_SUCCESS'

export const CHANGE_PRODUCT_SUCCESS='CHANGE_PRODUCT_SUCCESS'

export const SORT_PRODUCTS_SUCCESS='SORT_PRODUCTS_SUCCESS'

export const FILTER_PRODUCT_BY_NAME_SUCCESS='FILTER_PRODUCT_BY_NAME_SUCCESS'
export const FILTER_PRODUCT_BY_NAME_FAIL='FILTER_PRODUCT_BY_NAME_FAIL'

export const SEARCH_PRODUCT_SUCCESS='SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_FAIL='SEARCH_PRODUCT_FAIL'